### PR TITLE
Simplified problem 1 implementations; added more comments/testing

### PR DESCRIPTION
**Pull request by osu-mp**
Simplified some of the implementations of the list functions
Made it so that the problem 1 testing file can import the file we will submit

### CODE REVIEW

**Review by caitlynplewis — APPROVED** [review]
Both the comments and the simplifications are easy to follow, great changes.

**Comment by psulliv** [comment]
ship it!

**Review by psulliv — APPROVED** [review]
LGTM, I've got a version of the bag implementation too if you want to see a different version

**Comment by osu-mp** [comment]
> 

Yeah, I'd be interested to see it. You could upload the other version of the bag as a different file.

**Comment by psulliv** [comment]
> > 
> 
> Yeah, I'd be interested to see it. You could upload the other version of the bag as a different file.

~ok, I'll add it in the hw1 directory~
https://gist.github.com/psulliv/0dab30beaf620c4360ac2fc30405a6e7
I figured a gist is easier

**Pull request merged**
