### PR TITLE
updates Pars/Seq to be an array type 

### PR DESCRIPTION
**Pull request by psulliv**
```
>./1_mini_logo
./1_mini_logo
"part b: vector function"
Def "vector" (Pars ["x1","y1","x2","y2"]) (Seq (Pen Up) (Seq (MoveTo (Names ("x1","y1"))) (Seq (Pen Down) (Seq (MoveTo (Names ("x2","y2"))) (Pen Up)))))
"part c: steps 1"
Seq (Pen Up) (Seq (MoveTo (Ints (1,1))) (Seq (Pen Down) (Seq (MoveTo (Ints (0,1))) (MoveTo (Ints (0,0))))))
"part c: steps 4"
Seq (Pen Up) (Seq (MoveTo (Ints (4,4))) (Seq (Pen Down) (Seq (MoveTo (Ints (3,4))) (Seq (MoveTo (Ints (3,3))) (Seq (Pen Up) (Seq (MoveTo (Ints (3,3))) (Seq (Pen Down) (Seq (MoveTo (Ints (2,3))) (Seq (MoveTo (Ints (2,2))) (Seq (Pen Up) (Seq (MoveTo (Ints (2,2))) (Seq (Pen Down) (Seq (MoveTo (Ints (1,2))) (Seq (MoveTo (Ints (1,1))) (Seq (Pen Up) (Seq (MoveTo (Ints (1,1))) (Seq (Pen Down) (Seq (MoveTo (Ints (0,1))) (MoveTo (Ints (0,0)))))))))))))))))))))
```

### CODE REVIEW

**Comment by psulliv** [comment]
Also changing `Seq Expr Expr ` to `Seq [Expr]` according to section 3.4.3 of the partial lecture notes

**Comment by psulliv** [comment]
```
λ> steps 4
Seq [Pen Up,MoveTo (Ints (1,1)),Pen Down,MoveTo (Ints (0,1)),MoveTo (Ints (0,0)),Pen Up,MoveTo (Ints (2,2)),Pen Down,MoveTo (Ints (1,2)),MoveTo (Ints (1,1)),Pen Up,MoveTo (Ints (3,3)),Pen Down,MoveTo (Ints (2,3)),MoveTo (Ints (2,2)),Pen Up,MoveTo (Ints (4,4)),Pen Down,MoveTo (Ints (3,4)),MoveTo (Ints (3,3))]
λ> steps 1
Seq [Pen Up,MoveTo (Ints (1,1)),Pen Down,MoveTo (Ints (0,1)),MoveTo (Ints (0,0))]
```

**Comment by psulliv** [comment]
Also:
```
λ> vector
Def "vector" (Pars ["x1","y1","x2","y2"]) (Seq [Pen Up,MoveTo (Names ("x1","y1")),Pen Down,MoveTo (Names ("x2","y2")),Pen Up])
```

**Review by caitlynplewis — APPROVED** [review]
Loving the gradual death of the parentheses.

**Review by osu-mp — APPROVED** [review]
Looks good. I'll go ahead and merge this in and then update the hw2_group2.hs file with the changes.

**Pull request merged**
